### ISSUE TITLE
Should this work on 4.6.27 ?

### ISSUE THREAD

**Issue by joemcl** [eileenmcnaughton/nz.co.fuzion.activitypropagate#1]
Eileen, looking at your commit from a month ago - you described it as "Update call to setStatus to reflect 4.7 code". Should this work on 4.6.27 - or only on 4.7.X ? Pete updated it on my.cany.org that is running 4.6.27 . Thanks.

**Comment by eileenmcnaughton** [comment]
Looks like it changed it to use a function that has been around for a while - so it should be fine

**Comment by joemcl** [comment]
OK, thanks @eileenmcnaughton . We are still having problems with the import we hoped the commit would fix - see our redmine issue 11902.

**Comment by joemcl** [comment]
Hey @eileenmcnaughton just to update and close this issue - the code works fine - the problem was with the way we had created the import file. Once we figured that out, the Activity import worked as expected.

**Comment by eileenmcnaughton** [comment]
thanks
